apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kubernetes-component
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component
    jenkins.io/job-full-name: updateECL_WFT
spec:
  lifecycle: production
  owner: guests
  type: service
